### ISSUE TITLE
Any chance for a quick setup guide? :)

### ISSUE THREAD

**Issue by stephanlinke87** [florian-h05/webrtc-sip-gw#1] opened 2022-12-03 13:16 UTC
Hi Nanosonde, 

I'm somewhat struggling with the overhead of SIP Hass-Card (asterisk and co) with my doorbird intercom and I already had it working with my Fritzbox. Is there any chance you could post a quick howto on how to get this gateway working by any chance? :) 

Thanks in advance,
Stephan

**Comment by nanosonde** [comment] 2022-12-04 08:13
Hi Stephan!
Have a look at the forked version of this repo.
@florian-h05

BTW: 
@florian-h05 Do you have any plans of opening a PR with your additions? I have also seen that you added a license file and claim to be the original author.
I would be happy to accept a PR and also clarify the license situation.

**Comment by stephanlinke87** [comment] 2022-12-04 08:37
Awesome, thanks for the quick follow up on this! I'll try this right away :)

**Comment by florian-h05** [comment] 2022-12-04 09:03
@nanosonde 
> Do you have any plans of opening a PR with your additions?

Originally, I had this plan, but I wanted to add an ENV to let the user change the domainname of the SIP server, but I guess that’s not going to happen soon (I currently don’t have the time to develop the Docker Container).

> I have also seen that you added a license file and claim to be the original author.

Yes, but I am wondering that I haven’t added any note to you being the original author. If you tell me your real name I can add you.
I made larger changes, as the entrypoint did not work for me, upgraded the container to Debian 11 etc.

> I would be happy to accept a PR and also clarify the license situation.

I can open a PR now, I just have to modify a few naming things to match your repo (I’d like to publish it to GitHub Docker Registry).
Regarding the license situation: if you don’t have any preference, I’d keep MIT and state something like: `Copyright 2022 your name & Florian Hotze`.

**Comment by nanosonde** [comment] 2022-12-04 09:30
I though about it again.
Taking into account my available time, I think it would be best if you would take over the project. What do you think?

Also I should mention that I am also not the original author of the config files.
I took the ideas from here: https://github.com/havfo/WEBRTC-to-SIP

So if you want to maintain this, I would either delete my repo or transfer ownership to you. 
So that other people will find your updated repo if they follow the old links, it would be best to transfer ownership.

Concerning my real name: I would prefer to stay in the dark. 😉

**Comment by florian-h05** [comment] 2022-12-04 09:46
I can take over the project, as I am using it everyday I will keep it in a working condition.

> Also I should mention that I am also not the original author of the config files.
I took the ideas from here: https://github.com/havfo/WEBRTC-to-SIP

Okay, that adds another note to the license.

> So that other people will find your updated repo if they follow the old links, it would be best to transfer ownership.

I agree 👍 Can I rename a transfered repo without breaking existing links? Because I’d like to give it my slightly more descriptive name (webrtc-sip-gw instead of sip-gw). I can merge my changes into your repo after the transfer.

> Concerning my real name: I would prefer to stay in the dark. 😉

No problem, then I‘ll use your GitHub username together with a short note

**Comment by nanosonde** [comment] 2022-12-04 10:39
Mhmm, I get this if I start the transfer:
![grafik](https://user-images.githubusercontent.com/2073569/205486098-2d936eca-8ab9-41e6-9e53-7d7b191ba03a.png)

**Comment by nanosonde** [comment] 2022-12-04 10:41
Maybe I should just delete it.

If I remember correctly, I have only mentioned it on one forum.
There are two other people who forked the project, but did not add anything.
So maybe just a backup.

**Comment by florian-h05** [comment] 2022-12-04 10:41
I guess the problem is my fork.
I‘ll open a PR upstream to your repo, please merge is using the `Rebase and Merge` option. Then I‘ll delete my fork and we can transfer the repo.

**Comment by nanosonde** [comment] 2022-12-04 11:03
Ok, Rebased and merged.

I am ready to transfer the repo.

**Comment by florian-h05** [comment] 2022-12-04 11:04
@nanosonde I‘ve just deleted my fork, so you can try the transfer again.

**Comment by florian-h05** [comment] 2022-12-04 11:06
@nanosonde It worked, thanks 👍

**Comment by nanosonde** [comment] 2022-12-04 11:09
Take care of yourself my little "webrtc-gw". 
I will always be there. 😉

**Comment by florian-h05** [comment] 2022-12-04 11:10
I‘ll take care of it.
@nanosonde FYI: You are listed as a collaborator and you therefore should have elevated rights and push access.

**Comment by nanosonde** [comment] 2022-12-04 11:10
Closing this.

**Closed by nanosonde** 2022-12-04 11:10 UTC

**Comment by nanosonde** [comment] 2022-12-04 11:11
BTW; redirect seems to work. Just checked it.
